language: node_js

node_js:
  - 6

env:
  - CXX=g++-4.8

sudo: required

before_install:
  - curl -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz > ffmpeg
  - chmod +x ffmpeg
  - sudo mv ffmpeg /usr/local/bin

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

after_success:
  - bash <(curl -s https://codecov.io/bash)