dist: trusty
sudo: false

language: node_js

node_js:
  - 6

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - trusty-media
    packages:
      - g++-4.8
      - ffmpeg

after_success:
  - bash <(curl -s https://codecov.io/bash)