language: node_js

node_js:
  - 6

env:
  - CXX=g++-4.8

sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - jon-severinsson-ffmpeg
    packages:
      - g++-4.8
      - ffmpeg

after_success:
  - bash <(curl -s https://codecov.io/bash)